### ISSUE TITLE
Data assimilation notebooks

### ISSUE THREAD

**Issue by dhruvbalwada** [m2lines/L96_demo#119]
Hi @feiyulu and @MitchBushuk and @William-gregory - 

You had all shown some interest in improving the DA section of our demo (https://m2lines.github.io/L96_demo/notebooks/DA_demo_L96.html). Would it be possible for you all to self-organize and split the work around this? I am happy to discuss more on this as needed. I think Mitch has some slides, so some of the work might just be in converting from slides to notebook format. Maybe skimming the initial part of the machine learning section in the book, can help provide a sense of what the expectations of pedagogy are. 

I think the goal is to try to and wrap everything up before the end of the month. I hope this is not too much of an ask.

**Comment by feiyulu** [comment]
Hi @dhruvbalwada 

In terms of the code part, where do you think it needs improvement or more documentation?

**Comment by dhruvbalwada** [comment]
Honestly, since I am not an expert in DA - I can't really tell you.  
If you take a first pass at adding an intro, I will look over it and then tell you if I understood it. Maybe the expectation should be that someone who knows something about modeling and math (beginnner like me) but not much experience with DA can follow. You will see that this is roughly how the machine learning intro was structured. 
What do you think?

**Comment by NoraLoose** [comment]
Sure, I'm happy to help. @feiyulu, @MitchBushuk, @William-gregory have you already discussed what still needs to be done?

**Comment by feiyulu** [comment]
Hi @NoraLoose, I think the plan is to adapt the slides we used during the demo into markdowns at the beginning of the notebook. Then the code might need a bit more documentation and streamlining. 

Hi @dhruvbalwada, sorry I won't be able to work on this before the end of June. I had to finish a couple of things after the annual meeting and will have some time off until after July 4th. I will have time to work on this in July.

**Comment by MitchBushuk** [comment]
Hi all, the slides we used for the presentation are here: https://github.com/MitchBushuk/L96_demo/blob/main/slides/M2LInES%20L96%20DA%20Demo.pdf 

These show how DA works in the 1-D case, and then introduce the L96 DA toy problem. I am not claiming they are fully complete, but I think something like this would be a good starting point for the notebook. In addition to the slide content, I think it would be useful to (briefly) describe how the covariance matrix is obtained in 3D-VAR, EnKF, and Hybrid-EnKF, since these all appear in the notebook. Also, a few lines on the concepts of localization and inflation would be helpful, since these are also in the notebook.

I am busy with some deadlines the next few weeks, but think I may have a bit more time in July (pre-baby) to work on this.

**Comment by dhruvbalwada** [comment]
Hi all, was wondering if there were any updates on this?

**Comment by feiyulu** [comment]
> 

Hi Mitch, it seems like your repository is private. Could you share the access?

**Comment by MitchBushuk** [comment]
@feiyulu, I just shared access. Let me know if you have any issues.

**Comment by feiyulu** [comment]
> Hi all, was wondering if there were any updates on this?

Hi @dhruvbalwada , I'm starting to add some description to the notebook. This is my first new commit:
https://github.com/feiyulu/L96_demo/commit/eb1ef925b2e998795c409cc81c2291f53e21c3eb

Do you think this is in the right direction? Since I'm not very familiar with Markdown, it might require some editing eventually.

**Comment by dhruvbalwada** [comment]
Also don't worry too much about the markdown editing, we will be able to do that later. @IamShubhamGupto is an expert in that and can help sort it out once all the information content is in.

**Comment by dhruvbalwada** [comment]
Also might be good to reference these tutorials (or similar ones) in the notebook somewhere: https://dart.ucar.edu/tutorials/

**Comment by dhruvbalwada** [comment]
@feiyulu - any updates on the status of this notebook?

**Comment by feiyulu** [comment]
> @feiyulu - any updates on the status of this notebook?

Yes, I did make some more changes a couple of weeks ago. I moved all the functions to the python module file to declutter the notebook, and added some explanation in the notebook.

**Comment by dhruvbalwada** [comment]
Is it ready to make a pull request then to the main L96? or are you planning to make some more changes before?

**Comment by feiyulu** [comment]
I think I can do a PR and check how it looks so far.
