### ISSUE TITLE
Execution Failed: DA_demo_L96.ipynb

### ISSUE THREAD

**Issue by rabernat** [m2lines/L96_demo#40]
https://github.com/m2lines/L96_demo/runs/6475236874?check_suite_focus=true#step:8:68

**Comment by adcroft** [comment]
This is because the file `B_clim_L96s.npy` needs to exist, which is the covariance matrix for a long climatogical run of the single time-scale model. I think this file was previously in the repo. The other covariance dfile `B_clim_L96.npy` is for the two time-scale model and is created in the notebook on the fly - it probably does not need to be written to disk and then loaded. I see no reason to not calculate the single time-scale covariance on the fly too. @feiyulu , is my interpretation correct?
